Player_Vlad = Player()
Player_Vlad:AddBoundingBox(BBoundingBox(Player_Vlad, 0, 15, 17, 30))
Player_Vlad:AddBodyBoundingBox(EBoundingBox(Player_Vlad, EBoundingBoxType.Body, 0, 15, 17, 30))
Player_Vlad:AddAnimation(Create:Animation("Vlad_N_N"), MovingState.Normal, Direction.N)
Player_Vlad:AddAnimation(Create:Animation("Vlad_S_N"), MovingState.Normal, Direction.S)
Player_Vlad:AddAnimation(Create:Animation("Vlad_E_N"), MovingState.Normal, Direction.E)
Player_Vlad:AddAnimation(Create:Animation("Vlad_O_N"), MovingState.Normal, Direction.O)
Player_Vlad:AddAnimation(Create:Animation("Vlad_NE_N"), MovingState.Normal, Direction.NE)
Player_Vlad:AddAnimation(Create:Animation("Vlad_NO_N"), MovingState.Normal, Direction.NO)
Player_Vlad:AddAnimation(Create:Animation("Vlad_SE_N"), MovingState.Normal, Direction.SE)
Player_Vlad:AddAnimation(Create:Animation("Vlad_SO_N"), MovingState.Normal, Direction.SO)
Player_Vlad:AddAnimation(Create:Animation("Vlad_N_W"), MovingState.Walking, Direction.N)
Player_Vlad:AddAnimation(Create:Animation("Vlad_S_W"), MovingState.Walking, Direction.S)
Player_Vlad:AddAnimation(Create:Animation("Vlad_E_W"), MovingState.Walking, Direction.E)
Player_Vlad:AddAnimation(Create:Animation("Vlad_O_W"), MovingState.Walking, Direction.O)
Player_Vlad:AddAnimation(Create:Animation("Vlad_NE_W"), MovingState.Walking, Direction.NE)
Player_Vlad:AddAnimation(Create:Animation("Vlad_NO_W"), MovingState.Walking, Direction.NO)
Player_Vlad:AddAnimation(Create:Animation("Vlad_SE_W"), MovingState.Walking, Direction.SE)
Player_Vlad:AddAnimation(Create:Animation("Vlad_SO_W"), MovingState.Walking, Direction.SO)
Player_Vlad:AddAnimation(Create:Animation("Vlad_N_R"), MovingState.Running, Direction.N)
Player_Vlad:AddAnimation(Create:Animation("Vlad_S_R"), MovingState.Running, Direction.S)
Player_Vlad:AddAnimation(Create:Animation("Vlad_E_R"), MovingState.Running, Direction.E)
Player_Vlad:AddAnimation(Create:Animation("Vlad_O_R"), MovingState.Running, Direction.O)
Player_Vlad:AddAnimation(Create:Animation("Vlad_NE_R"), MovingState.Running, Direction.NE)
Player_Vlad:AddAnimation(Create:Animation("Vlad_NO_R"), MovingState.Running, Direction.NO)
Player_Vlad:AddAnimation(Create:Animation("Vlad_SE_R"), MovingState.Running, Direction.SE)
Player_Vlad:AddAnimation(Create:Animation("Vlad_SO_R"), MovingState.Running, Direction.SO)
return Player_Vlad