NPC_Vlad = NPC()
NPC_Vlad:AddBoundingBox(BBoundingBox(NPC_Vlad, 0, 15, 17, 30))
NPC_Vlad:AddBodyBoundingBox(EBoundingBox(NPC_Vlad, EBoundingBoxType.Body, 0, 15, 17, 30))
NPC_Vlad:AddAnimation(Create:Animation("Vlad_N_N"), MovingState.Normal, Direction.N)
NPC_Vlad:AddAnimation(Create:Animation("Vlad_S_N"), MovingState.Normal, Direction.S)
NPC_Vlad:AddAnimation(Create:Animation("Vlad_E_N"), MovingState.Normal, Direction.E)
NPC_Vlad:AddAnimation(Create:Animation("Vlad_O_N"), MovingState.Normal, Direction.O)
NPC_Vlad:AddAnimation(Create:Animation("Vlad_NE_N"), MovingState.Normal, Direction.NE)
NPC_Vlad:AddAnimation(Create:Animation("Vlad_NO_N"), MovingState.Normal, Direction.NO)
NPC_Vlad:AddAnimation(Create:Animation("Vlad_SE_N"), MovingState.Normal, Direction.SE)
NPC_Vlad:AddAnimation(Create:Animation("Vlad_SO_N"), MovingState.Normal, Direction.SO)
NPC_Vlad:AddAnimation(Create:Animation("Vlad_N_W"), MovingState.Walking, Direction.N)
NPC_Vlad:AddAnimation(Create:Animation("Vlad_S_W"), MovingState.Walking, Direction.S)
NPC_Vlad:AddAnimation(Create:Animation("Vlad_E_W"), MovingState.Walking, Direction.E)
NPC_Vlad:AddAnimation(Create:Animation("Vlad_O_W"), MovingState.Walking, Direction.O)
NPC_Vlad:AddAnimation(Create:Animation("Vlad_NE_W"), MovingState.Walking, Direction.NE)
NPC_Vlad:AddAnimation(Create:Animation("Vlad_NO_W"), MovingState.Walking, Direction.NO)
NPC_Vlad:AddAnimation(Create:Animation("Vlad_SE_W"), MovingState.Walking, Direction.SE)
NPC_Vlad:AddAnimation(Create:Animation("Vlad_SO_W"), MovingState.Walking, Direction.SO)
NPC_Vlad:AddAnimation(Create:Animation("Vlad_N_R"), MovingState.Running, Direction.N)
NPC_Vlad:AddAnimation(Create:Animation("Vlad_S_R"), MovingState.Running, Direction.S)
NPC_Vlad:AddAnimation(Create:Animation("Vlad_E_R"), MovingState.Running, Direction.E)
NPC_Vlad:AddAnimation(Create:Animation("Vlad_O_R"), MovingState.Running, Direction.O)
NPC_Vlad:AddAnimation(Create:Animation("Vlad_NE_R"), MovingState.Running, Direction.NE)
NPC_Vlad:AddAnimation(Create:Animation("Vlad_NO_R"), MovingState.Running, Direction.NO)
NPC_Vlad:AddAnimation(Create:Animation("Vlad_SE_R"), MovingState.Running, Direction.SE)
NPC_Vlad:AddAnimation(Create:Animation("Vlad_SO_R"), MovingState.Running, Direction.SO)
return NPC_Vlad