Animation_ExplosionTest = Animation()
Animation_ExplosionTest.BasePoint = Vector2(80, 65)
Animation_ExplosionTest.ComparisonPointYType = ComparisonPointYType.Center
Animation_ExplosionTest.StopFrame = 0
Animation_ExplosionTest.FrameRate = 20
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest0"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest1"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest2"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest3"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest4"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest5"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest6"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest7"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest8"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest9"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest10"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest11"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest12"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest13"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest14"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest15"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest16"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest17"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest18"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest19"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest20"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest21"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest22"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest23"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest24"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest25"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest26"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest27"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest28"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest29"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest30"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest31"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest32"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest33"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest34"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest35"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest36"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest37"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest38"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest39"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest40"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest41"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest42"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest43"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest44"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest45"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest46"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest47"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest48"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest49"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest50"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest51"))
Animation_ExplosionTest:AddFrame(Create:Texture("Animation_ExplosionTest52"))
return Animation_ExplosionTest