Animation_ExplosionTest_2_ = Animation()
Animation_ExplosionTest_2_.BasePoint = Vector2(0, 0)
Animation_ExplosionTest_2_.ComparisonPointYType = ComparisonPointYType.Bottom
Animation_ExplosionTest_2_.StopFrame = 0
Animation_ExplosionTest_2_.FrameRate = 8
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_0"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_1"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_2"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_3"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_4"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_5"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_6"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_7"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_8"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_9"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_10"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_11"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_12"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_13"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_14"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_15"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_16"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_17"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_18"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_19"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_20"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_21"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_22"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_23"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_24"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_25"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_26"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_27"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_28"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_29"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_30"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_31"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_32"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_33"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_34"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_35"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_36"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_37"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_38"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_39"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_40"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_41"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_42"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_43"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_44"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_45"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_46"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_47"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_48"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_49"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_50"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_51"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_52"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_53"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_54"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_55"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_56"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_57"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_58"))
Animation_ExplosionTest_2_:AddFrame(Create:Texture("Animation_ExplosionTest_2_59"))
return Animation_ExplosionTest_2_