SERVER_IO_TIMEOUT = 5000
SERVER_MAXPLAYER = 50

SERVER_IP = "127.0.0.1"
SERVER_PORT = 5321

DEFAULT_WALK_VELOCITY = 150.0
PERSONNAGE_RUN_VELOCITY_FACTOR = 1.5
ANIMATION_DEFAULT_FRAMERATE = 8
ANIMATION_DEFAULT_STOPFRAME = 0
DEFAULT_DIRECTION = Direction.S
INIT_MAP = "m1"
WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 680
WINDOW_STYLE = Styles.Close
DEFAULT_FONT = "REFSAN.TTF"

GROUND_DRAW_MARGIN = 1
TILE_SIZE = 32

JOYSTICK_WALK_SENSIBILITY = 25.0
JOYSTICK_RUN_SENSIBILITY = 90.0

KEY_UP = 	{ KeyCode.W }
KEY_RIGHT = 	{ KeyCode.D }
KEY_DOWN = 	{ KeyCode.S }
KEY_LEFT = 	{ KeyCode.A }
KEY_ACTION = 	{ KeyCode.Return }
KEY_BACK = 	{ KeyCode.Back }
KEY_MISC = 	{ KeyCode.X }

KEY_UP2 = 	{ KeyCode.Space }
KEY_RIGHT2 = 	{ KeyCode.Space }
KEY_DOWN2 = 	{ KeyCode.Space }
KEY_LEFT2 = 	{ KeyCode.Space }
KEY_ACTION2 = 	{ KeyCode.Space }

KEY_SPECIAL0 = 	{ KeyCode.Space }
KEY_SPECIAL1 = 	{ KeyCode.Space }
KEY_SPECIAL2 = 	{ KeyCode.Space }
KEY_SPECIAL3 = 	{ KeyCode.Space }
KEY_SPECIAL4 = 	{ KeyCode.Space }
KEY_SPECIAL5 = 	{ KeyCode.Space }
KEY_SPECIAL6 = 	{ KeyCode.Space }
KEY_SPECIAL7 = 	{ KeyCode.Space }
KEY_SPECIAL8 = 	{ KeyCode.Space }
KEY_SPECIAL9 = 	{ KeyCode.Space }