SERVER_IO_TIMEOUT = 5000
SERVER_MAXPLAYER = 50

SERVER_IP = "192.168.1.14"
SERVER_PORT = 5321

DEFAULT_WALK_VELOCITY = 150.0
PERSONNAGE_RUN_VELOCITY_FACTOR = 1.5
ANIMATION_DEFAULT_FRAMERATE = 8
ANIMATION_DEFAULT_STOPFRAME = 0
DEFAULT_DIRECTION = Direction.S
INIT_MAP = "combat_test"
WINDOW_WIDTH = 640
WINDOW_HEIGHT = 480
WINDOW_STYLE = Styles.Close
DEFAULT_FONT = "REFSAN.TTF"

GROUND_DRAW_MARGIN = 1
TILE_SIZE = 32

JOYSTICK_WALK_SENSIBILITY = 25.0
JOYSTICK_RUN_SENSIBILITY = 90.0

KEY_UP = 	{ Key.Up }
KEY_RIGHT = 	{ Key.Right }
KEY_DOWN = 	{ Key.Down }
KEY_LEFT = 	{ Key.Left }
KEY_ACTION = 	{ Key.Return }
KEY_BACK = 	{ Key.Back }
KEY_MISC = 	{ Key.X }

KEY_UP2 = 	{ Key.W }
KEY_RIGHT2 = 	{ Key.D }
KEY_DOWN2 = 	{ Key.S }
KEY_LEFT2 = 	{ Key.A  }
KEY_ACTION2 = 	{ Key.Space }

KEY_SPECIAL0 = 	{ Key.G }
KEY_SPECIAL1 = 	{ Key.A }
KEY_SPECIAL2 = 	{ Key.M }
KEY_SPECIAL3 = 	{  }
KEY_SPECIAL4 = 	{  }
KEY_SPECIAL5 = 	{  }
KEY_SPECIAL6 = 	{  }
KEY_SPECIAL7 = 	{  }
KEY_SPECIAL8 = 	{  }
KEY_SPECIAL9 = 	{  }