SERVER_IO_TIMEOUT = 5000
SERVER_MAXPLAYER = 50

SERVER_IP = "127.0.0.1"
SERVER_PORT = 5321

DEFAULT_WALK_VELOCITY = 150.0
PERSONNAGE_RUN_VELOCITY_FACTOR = 1.5
ANIMATION_DEFAULT_FRAMERATE = 8
ANIMATION_DEFAULT_STOPFRAME = 0
DEFAULT_DIRECTION = Direction.S
INIT_MAP = "combat_test"
WINDOW_WIDTH = 640
WINDOW_HEIGHT = 480
WINDOW_STYLE = Styles.Close
DEFAULT_FONT = "REFSAN.TTF"

GROUND_DRAW_MARGIN = 1
TILE_SIZE = 32

JOYSTICK_WALK_SENSIBILITY = 25.0
JOYSTICK_RUN_SENSIBILITY = 90.0

KEY_UP = 	{ KeyCode.Up }
KEY_RIGHT = 	{ KeyCode.Right }
KEY_DOWN = 	{ KeyCode.Down }
KEY_LEFT = 	{ KeyCode.Left }
KEY_ACTION = 	{ KeyCode.Return }
KEY_BACK = 	{ KeyCode.Back, KeyCode.Escape }
KEY_MISC = 	{ KeyCode.X }

KEY_UP2 = 	{ KeyCode.W }
KEY_RIGHT2 = 	{ KeyCode.D }
KEY_DOWN2 = 	{ KeyCode.S }
KEY_LEFT2 = 	{ KeyCode.A  }
KEY_ACTION2 = 	{ KeyCode.Space }

KEY_SPECIAL0 = 	{ KeyCode.G }
KEY_SPECIAL1 = 	{ KeyCode.A }
KEY_SPECIAL2 = 	{ KeyCode.M }
KEY_SPECIAL3 = 	{  }
KEY_SPECIAL4 = 	{  }
KEY_SPECIAL5 = 	{  }
KEY_SPECIAL6 = 	{  }
KEY_SPECIAL7 = 	{  }
KEY_SPECIAL8 = 	{  }
KEY_SPECIAL9 = 	{  }